spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:${user.home}/spring-boot-h2-db
    username: sa
    password: dreamer@2020
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    
  # Javamail settings
  mail:
    host: mail.gss.com.tw
    port: 25
    #username: 
    #password: 

    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          from: noreply@gss.com.tw
          auth: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          # TLS , port 587
          #starttls.enable: true
           
          # SSL, post 465
          #socketFactory:
            #port: 465
            #class: javax.net.ssl.SSLSocketFactory

checkin-config:
  token-url: https://gssportal.gss.com.tw/BeHorApi/token
  checkin-url: https://gssportal.gss.com.tw/BeHorApi/api/Attend/Checkin
  holidays: 2020/1/1,2020/1/23~2020/1/29,2020/2/28~2020/3/1,2020/4/2~2020/4/5,2020/5/1,2020/6/25~2020/6/28,2020/10/1~2020/10/4,2020/10/9~2020/10/11,2021/1/1~2021/1/3
  checkin-time: '08:30'
  checkout-time: '17:30'
  enabled: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:${user.home}/spring-boot-h2-test-db
    username: sa
    password: dreamer-tester@2020
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create

